lib/global_reader_project_web/router.ex
defmodule GlobalReaderProjectWeb.Router do
  use GlobalReaderProjectWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  if Mix.env == :dev do
    forward "/sent_emails", Bamboo.EmailPreviewPlug
  end

  scope "/", GlobalReaderProjectWeb do
    pipe_through :browser

    get "/", PageController, :index
    resources "/users", UserController, [:index, :show]
    get "/users/summary/info", UserController, :get_user_info
    resources "/login", LoginController, only: [:index, :create]
    resources "/forgotpassword", PasswordRecoveryController, [:new, :create, :edit, :update]
  end

  # Other scopes may use custom stacks.
  # scope "/api", GlobalReaderProjectWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: GlobalReaderProjectWeb.Telemetry
    end
  end
end

lib/global_reader_project_web/templates/page/index.html.eex
<section class="phx-hero">
  <h1> <%= gettext "Welcome to %{name}!", name: "Global Reader" %></h1>
  <p>We uplift your business.</p>
</section>

<section class="row">
  <article class="column" style="width: 50;">

  </article>

  <article class="column">
    <div class="row" >
      <button class="button" style="margin-right: 5px;"
       onclick="location.href='<%= Routes.login_path(@conn, :index) %>';"
       >Login</button>

        <!--Static email path is used to demonstrate only-->
       <button class="button" style="margin-right: 5px;"
       onclick="location.href='http://localhost:4000/sent_emails';"
       >Emails</button>

        <button class="button" style="margin-right: 5px;"
       onclick="location.href='<%= Routes.user_path(@conn, :get_user_info) %>';"
       >User Summary</button>
    </div>
  </article>

  <article class="column" style="width: 50;">

  </article>
</section>