lib/global_reader_project_web/router.ex
defmodule GlobalReaderProjectWeb.Router do
  use GlobalReaderProjectWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  if Mix.env == :dev do
    forward "/sent_emails", Bamboo.EmailPreviewPlug
  end

  scope "/", GlobalReaderProjectWeb do
    pipe_through :browser

    get "/", PageController, :index
    resources "/users", UserController, [:index, :show]
    get "/users/summary/info", UserController, :get_user_info
    resources "/login", LoginController, only: [:index, :create]
    resources "/forgotpassword", PasswordRecoveryController, [:new, :create, :edit, :update]
  end

  # Other scopes may use custom stacks.
  # scope "/api", GlobalReaderProjectWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: GlobalReaderProjectWeb.Telemetry
    end
  end
end

lib/global_reader_project_web/controllers/login_controller.ex
defmodule GlobalReaderProjectWeb.LoginController do
  use GlobalReaderProjectWeb, :controller

  def index(conn, _params) do
    render(conn, "login.html")
  end

  def create(conn, _params) do
    render(conn, "login.html")
  end
end

lib/global_reader_project_web/views/login_view.ex
defmodule GlobalReaderProjectWeb.LoginView do
  use GlobalReaderProjectWeb, :view
end

lib/global_reader_project_web/templates/login/login.html.eex
<!-- Will modify this form once authetication is active -->
<!--This template is taken from w3schools.com-->
<form method="post">

  <div class="container">
    <label for="uname"><b>Username</b></label>
    <input type="text" placeholder="Enter Username" name="uname" required>

    <label for="psw"><b>Password</b></label>
    <input type="password" placeholder="Enter Password" name="psw" required>

    <button type="submit">Login</button>
    <label>
      <input type="checkbox" checked="checked" name="remember"> Remember me
    </label>
  </div>

  <div class="container" style="background-color:#f1f1f1">
    <span class="psw"><a href="<%= Routes.password_recovery_path(@conn, :new) %>">Forgot password?</a></span>
  </div>
</form>